Algoritmo "ContadorSalto"

Var

   valor,salto,contador:inteiro

Inicio

      EscrevaL("Informe até quanto deseja Contar: ")
      Leia(valor)
      Escreva("Informe o valor do Salto: ")
      Leia(salto)
      
      contador <- 0
               Enquanto (contador <= valor) faca
                        EscrevaL(contador)
                        contador <- contador + salto
               FimEnquanto
      


Fimalgoritmo