Algoritmo "Fibonacci"


Var

  C,NA,NB,NC:Inteiro

Inicio

  NA <- 0
  NB <- 1
  NC <- 1

      Para C <- 0 ate 15 faca
           Escreva(NA)
           Escreva(NB)
           Escreva(NC)
           NA <- NB + NC
           NB <- NC + NA
           NC <- NA + NB
      FimPara

      // Muito feliz por conseguir chegar nessa lógica, precisei fazer um
      // esboço no meu caderno para conseguir resolver. *Vivaaaa*


Fimalgoritmo